import {Check,Handshake,Search,Bell,ShieldCheck,FileText,LogIn,Eye} from 'lucide-react';
import type {Member,Identity} from '@/lib/membership';
export function Landing({member,user,signInHref,registerHref}:{member:Member|null;user:Identity|null;signInHref:string;registerHref:string}){
 const active=member?.status==='Activo';return <main className="access-landing"><header className="landing-nav"><a href="/" className="landing-logo"><img src="/brand/logo-negro.png" alt="cuatroporciento"/></a><nav><a href="#beneficios">Beneficios</a><a href="#membresia">Membresía</a><a className="btn" href={active?'/inventario':signInHref} target={active?undefined:'_top'}>{active?'Entrar a la plataforma':'Iniciar sesión'}</a></nav></header>
 <section className="landing-hero"><div className="landing-story"><span className="eyebrow">Red de colaboración inmobiliaria</span><h1>El inmueble correcto.<br/>El asesor correcto.<br/><span>En el mismo lugar.</span></h1><p>Publica tu inventario, encuentra opciones para tus clientes y acuerda colaboraciones con otros asesores. Toda la información y sus respuestas quedan a la vista.</p><div className="landing-hero-photo"><img src="/demo-photos/garden.jpg" alt="Casa con jardín, imagen ilustrativa"/><span><Handshake size={19}/>Una red profesional para hacer negocios.</span></div></div>
 <aside className="landing-entry"><span className="eyebrow">Acceso a la red</span><h2>{active?'Tu espacio está listo':'Colabora con cuatroporciento'}</h2><p>{active?'Hola, '+member.name+'. Retoma tus solicitudes, publicaciones y colaboraciones.':'Una comunidad de asesores con ingreso validado. Solicita tu acceso o utiliza una invitación personal.'}</p><a className="btn landing-primary" href={active?'/inventario':signInHref} target={active?undefined:'_top'}><LogIn size={18}/>{active?'Abrir mi plataforma':'Iniciar sesión con ChatGPT'}</a>{user&&<small>Sesión: {user.email}</small>}<a className="btn secondary landing-guest" href="/explorar"><Eye size={18}/>Explorar como invitado</a><p className="guest-entry-caption">Conoce la plataforma sin registrarte. Recorrido de solo lectura.</p><div className="entry-divider"/><h3>¿Primera vez aquí?</h3><a className="btn secondary" href={registerHref}>Solicitar acceso / usar invitación</a><div className="entry-rules"><div><ShieldCheck size={19}/><p><strong>Sin invitación</strong>Tu registro pasa a revisión. El administrador autoriza tu entrada.</p></div><div><Check size={19}/><p><strong>Con un código válido</strong>Tu acceso se activa al completar el registro con el correo invitado.</p></div></div><small>Cada invitación es personal y se puede usar una sola vez.</small></aside></section>
 <section id="beneficios" className="landing-benefits"><div className="landing-section-head"><span className="eyebrow">Una red que trabaja contigo</span><h2>Menos búsquedas dispersas.<br/>Más información para colaborar.</h2></div><div className="benefit-grid">{[{icon:Search,title:'Inventario que puedes buscar',text:'Encuentra casas, departamentos, terrenos, bodegas y más por ubicación, precio y características.'},{icon:Bell,title:'Solicitudes que siguen activas',text:'Guarda lo que necesita tu cliente. Una opción compatible genera una alerta aunque tu búsqueda haya empezado sin resultados.'},{icon:Handshake,title:'Respuestas y condiciones claras',text:'Solicita una colaboración y recibe avisos cuando la aceptan, rechazan o piden una aclaración.'},{icon:FileText,title:'Fichas listas para tus clientes',text:'Comparte un PDF con fotos, información ordenada y la identidad de cuatroporciento.'}].map(({icon:Icon,title,text})=><article key={title}><Icon size={25}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section id="membresia" className="landing-pricing"><div><span className="eyebrow">Membresía mensual</span><h2>Tu lugar dentro de la red.</h2><p>El modelo de cuatroporciento es una suscripción para asesores. El ingreso está sujeto a validación o a una invitación autorizada.</p><p>Los planes para equipos se comunicarán cuando sus condiciones estén definidas.</p></div><article><div className="row between"><h3>Asesor</h3><span className="tag">En preparación</span></div><strong>Tarifa por definir</strong><p>Precio de lanzamiento y condiciones pendientes de confirmación.</p><ul>{['Consultar y publicar inventario','Solicitudes con historial y alertas','Colaboración entre asesores','Ficha PDF para clientes'].map(s=><li key={s}><Check size={16}/>{s}</li>)}</ul><a href={registerHref} className="btn">Solicitar acceso</a><small>Esta versión no realiza cobros.</small></article></section><footer className="landing-footer"><img src="/brand/isotipo-negro.png" alt=""/><span>cuatroporciento · Colaboración inmobiliaria</span><a href={active?'/inventario':signInHref} target={active?undefined:'_top'}>Entrar</a></footer></main>;
}
