'use client';
import {useState} from 'react';
import {Crown,House,ShieldCheck,Search,Building2,Layers,KeyRound} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {useDemo,DemoLink} from './platform-data';
import {inventoryStats,networkLevels} from '@/lib/network-levels';
import type {AdvisorProfile} from '@/lib/demo-model';
import {money,type Property} from '@/lib/real-estate';

export function LevelBadge({level,caption=false,context}:{level:number;caption?:boolean;context?:string}){return <span className={'level-badge level-'+level} title={(context?context+' · ':'')+networkLevels[level].name}>{level>=4&&<Crown size={13}/>}<span>{level?'Nivel '+level:'Inicial'}</span>{caption&&<span>· {networkLevels[level].name}</span>}</span>}
export function PropertyBadges({property,level}:{property:Property;level?:number}){return <div className="property-badges"><span className={'origin-badge '+(property.direct?'direct':'shared')}>{property.direct?'Directa':'Compartida'}</span>{property.exclusive&&<span className="origin-badge exclusive"><KeyRound size={11}/>Exclusiva</span>}{level!==undefined&&<LevelBadge level={level} context="Nivel del asesor responsable"/>}</div>}
export function LevelProgress({ownerId}:{ownerId:string}){const {properties}=useDemo();const stats=inventoryStats(ownerId,properties);return <div className="level-progress"><div className="row between"><LevelBadge level={stats.tier.level}/><strong>{stats.direct} directas activas</strong></div><h3>{stats.tier.name}</h3><Progress value={stats.progress} aria-label="Avance al siguiente nivel"/><p>{stats.next?'Faltan '+stats.remaining+' propiedades directas activas para el nivel '+stats.next.level+'.':'Alcanzaste el nivel más alto de la red.'}</p></div>}
export function LevelsPage(){const {actorId,guest}=useDemo();return <><section className="level-intro"><div><span className="eyebrow">Inventario directo</span><h2>Un nivel que crece con tu cartera.</h2><p>Cuenta la cantidad de propiedades directas que cada asesor tiene disponibles. Las compartidas y las publicaciones retiradas o pendientes de reconfirmación no suman al nivel.</p><DemoLink href="/red" className="text-link">Ver niveles de los asesores</DemoLink></div>{!guest&&<LevelProgress ownerId={actorId}/>}</section><div className="level-scale">{networkLevels.map(t=><article className={'level-step-card tier-'+t.level} key={t.level}><span className="level-medal">{t.level||<House size={25}/>}</span><LevelBadge level={t.level}/><h3>{t.name}</h3><strong>{t.range}</strong><p>propiedades directas activas</p></article>)}</div><div className="level-notes"><article className="panel"><Layers size={22}/><h3>La etiqueta de cada inmueble</h3><p><strong>Directa:</strong> el asesor declara contacto directo con el propietario. <strong>Compartida:</strong> interviene otro asesor. <strong>Exclusiva:</strong> declara una autorización exclusiva; es un dato adicional.</p></article><article className="panel"><ShieldCheck size={22}/><h3>Qué significa el nivel</h3><p>Es una medida de volumen de inventario, calculada automáticamente. No certifica la propiedad, sus documentos ni la calidad del servicio y no cambia la membresía contratada.</p></article></div></>}
export function AdvisorSheet({advisor,onClose,onProperty}:{advisor:AdvisorProfile|null;onClose:()=>void;onProperty:(p:Property)=>void}){const {properties,guest}=useDemo();const own=properties.filter(p=>p.ownerId===advisor?.id&&p.status==='Disponible');const stats=inventoryStats(advisor?.id||'',properties);return <Sheet open={!!advisor} onOpenChange={v=>{if(!v)onClose()}}><SheetContent className="brand-overlay advisor-sheet"><SheetHeader><span className="eyebrow">{guest?'Perfil ilustrativo':'Asesor de la red'}</span><SheetTitle>{advisor?.name}</SheetTitle><SheetDescription>{advisor?.agency}</SheetDescription></SheetHeader>{advisor&&<div className="advisor-sheet-content"><div className="row between"><span className="avatar advisor-avatar">{advisor.initials}</span><span className="tag">{guest?'Ejemplo de perfil':'Acceso validado'}</span></div><LevelProgress ownerId={advisor.id}/><div className="profile-inventory-stats">{[[stats.direct,'Directas'],[stats.shared,'Compartidas'],[stats.exclusive,'Exclusivas']].map(([count,label])=><div key={label}><strong>{count}</strong><span>{label}</span></div>)}</div><div className="advisor-zones"><span className="eyebrow">Zonas con inventario</span><div className="criteria">{Array.from(new Set(own.map(p=>p.zone))).map(z=><span key={z}>{z}</span>)}{!own.length&&<span>Sin publicaciones disponibles</span>}</div></div><div className="row between"><h3>Propiedades disponibles</h3><span className="tag gray">{own.length}</span></div><div className="advisor-property-list">{own.map(p=><button className="advisor-property" key={p.id} onClick={()=>{onClose();onProperty(p)}}><img src={p.image} alt=""/><span><strong>{p.title}</strong><small>{money(p.price)} · {p.zone}</small><PropertyBadges property={p}/></span></button>)}</div><p className="form-caption">El nivel usa las propiedades directas activas de este perfil. El origen y la exclusividad son declaraciones del responsable de cada publicación.</p>{guest&&<a className="btn" href="/registro">Solicitar acceso a la red</a>}</div>}</SheetContent></Sheet>}
export function AdvisorsPage({onProperty}:{onProperty:(p:Property)=>void}){const {networkProfiles,properties,guest}=useDemo();const [q,setQ]=useState(''),[level,setLevel]=useState('Todos'),[selected,setSelected]=useState<AdvisorProfile|null>(null);const advisors=networkProfiles.filter(a=>a.active!==false).filter(a=>[a.name,a.agency,...properties.filter(p=>p.ownerId===a.id).map(p=>p.zone)].join(' ').toLowerCase().includes(q.toLowerCase())).filter(a=>level==='Todos'||String(inventoryStats(a.id,properties).tier.level)===level);return <><div className="directory-toolbar"><div className="search-input"><Search size={18}/><input aria-label="Buscar asesor, agencia o zona" placeholder="Asesor, agencia o zona de trabajo" value={q} onChange={e=>setQ(e.target.value)}/></div><Select value={level} onValueChange={setLevel}><SelectTrigger aria-label="Nivel del asesor"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Todos">Todos los niveles</SelectItem>{networkLevels.map(t=><SelectItem value={String(t.level)} key={t.level}>{t.level?'Nivel '+t.level:'Inicial'} · {t.name}</SelectItem>)}</SelectContent></Select><DemoLink className="btn secondary" href="/niveles">Cómo funcionan los niveles</DemoLink></div><div className="advisor-grid">{advisors.map(a=>{const stats=inventoryStats(a.id,properties);const zones=Array.from(new Set(properties.filter(p=>p.ownerId===a.id&&p.status==='Disponible').map(p=>p.zone)));return <article className="panel advisor-card" key={a.id}><div className="row between"><span className="avatar advisor-avatar">{a.initials}</span><LevelBadge level={stats.tier.level}/></div><h3>{a.name}</h3><p>{a.agency}</p><div className="advisor-tier-name">{stats.tier.name}</div><div className="profile-inventory-stats"><div><strong>{stats.direct}</strong><span>Directas</span></div><div><strong>{stats.shared}</strong><span>Compartidas</span></div><div><strong>{stats.active}</strong><span>Disponibles</span></div></div><div className="criteria advisor-zones">{zones.length?zones.slice(0,3).map(z=><span key={z}>{z}</span>):<span>Sin inventario activo</span>}</div><button className="btn secondary" onClick={()=>setSelected(a)}><Building2 size={16}/>Ver perfil e inventario</button></article>})}</div>{!advisors.length&&<div className="panel admin-empty">No hay asesores con estos filtros.</div>}<div className="help-strip"><ShieldCheck size={18}/>{guest?'Estás viendo perfiles e inmuebles de ejemplo. Solicita acceso para colaborar con la red.':'El acceso validado y el nivel de inventario se muestran por separado. La autorización y disponibilidad de cada inmueble las declara su responsable.'}</div><AdvisorSheet advisor={selected} onClose={()=>setSelected(null)} onProperty={onProperty}/></>}
