'use client';
import {useState} from 'react';
import {Bell,Handshake,Layers,CheckCheck} from 'lucide-react';
import {useDemo} from './platform-data';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {CriteriaChips} from './requests';
import type {Property} from '@/lib/real-estate';
export function NotificationDigest(){const {notifications,navigate}=useDemo();const unread=notifications.filter(n=>!n.readAt);const latest=unread[0];return <button className={'alert-digest'+(latest?.kind==='collaboration'&&latest.status==='Rechazada'?' bad-news':'')} onClick={()=>navigate('/alertas')}><span className="digest-icon"><Bell size={21}/></span><span><strong>{unread.length?unread.length+' notificaciones sin leer':'Notificaciones y alertas'}</strong><small>{latest?(latest.kind==='collaboration'?latest.title+' · '+latest.propertyTitle:'Nueva opción para '+latest.requirementReference):'Aquí encontrarás las respuestas de colaboración y las opciones para tus solicitudes.'}</small></span><span className="digest-action">Abrir panel</span></button>}
export function NotificationsPanel({onProperty}:{onProperty:(p:Property)=>void}){const {guest,notifications,requirements,properties,collaborations,actorId,runAction,setReqId,setCollabTab,navigate,saving,loading,error}=useDemo();const [tab,setTab]=useState('Todas');const unread=notifications.filter(n=>!n.readAt),blocked=saving||loading||!!error;const list=notifications.filter(n=>tab==='Todas'||tab==='Sin leer'&&!n.readAt||tab==='Colaboraciones'&&n.kind==='collaboration'||tab==='Búsquedas'&&n.kind!=='collaboration');async function read(ids:string[]){if(guest)return true;for(let start=0;start<ids.length;start+=300){if(!await runAction({type:'notifications_read',actorId,ids:ids.slice(start,start+300)}))return false;}return true;}
 return <><div className="alert-overview"><div><Bell size={22}/><strong>{unread.length}</strong><span>Sin leer</span></div><div><Handshake size={22}/><strong>{notifications.filter(n=>n.kind==='collaboration').length}</strong><span>Colaboraciones</span></div><div><Layers size={22}/><strong>{notifications.filter(n=>n.kind!=='collaboration').length}</strong><span>Opciones para tus búsquedas</span></div></div><div className="results-header request-views"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line">{['Todas','Sin leer','Colaboraciones','Búsquedas'].map(t=><TabsTrigger value={t} key={t}>{t}</TabsTrigger>)}</TabsList></Tabs>{!guest&&unread.length>0&&<button className="btn secondary small" disabled={blocked} onClick={()=>void read(unread.map(n=>n.id))}><CheckCheck size={15}/>Marcar todas leídas</button>}</div>
 <div className="alerts-list">{list.length?list.map(n=>{const p=properties.find(p=>p.id===n.propertyId);const col=n.kind==='collaboration'?collaborations.find(c=>c.id===n.collaborationId):null;const r=n.kind!=='collaboration'?requirements.find(r=>r.id===n.requirementId):null;return <article className={'alert-card'+(!n.readAt?' unread':'')+(n.kind==='collaboration'&&n.status==='Rechazada'?' rejected':'')} key={n.id}><div className="alert-symbol">{n.kind==='collaboration'?<Handshake size={23}/>:<Layers size={23}/>}</div><div className="alert-card-body"><div className="row between"><span className={'tag '+(n.kind==='collaboration'&&n.status==='Rechazada'?'red':n.readAt?'gray':'')}>{n.kind==='collaboration'?n.title:'Posible coincidencia'}{!n.readAt?' · Nueva':''}</span><small>{new Date(n.createdAt).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'})}</small></div><h2>{p?.title||n.propertyTitle}</h2><p>{n.kind==='collaboration'?n.message:'Para tu búsqueda: '+(r?.reference||n.requirementReference)}</p>{n.kind!=='collaboration'&&<CriteriaChips labels={n.reasons}/>}<div className="request-card-actions">{col&&<button className="btn small" disabled={blocked} onClick={async()=>{if(await read(n.readAt?[]:[n.id])){setCollabTab(col.direction);navigate('/colaboraciones')}}}>Ver colaboración</button>}{r&&<button className="btn small" disabled={blocked} onClick={async()=>{if(await read(n.readAt?[]:[n.id])){setReqId(r.id);navigate('/solicitudes?solicitud='+encodeURIComponent(r.id))}}}>Ver opciones de la solicitud</button>}{p&&<button className="btn secondary small" disabled={blocked} onClick={async()=>{if(await read(n.readAt?[]:[n.id]))onProperty(p)}}>Ver propiedad</button>}{!guest&&!n.readAt&&<button className="text-link" disabled={blocked} onClick={()=>void read([n.id])}>Marcar leída</button>}</div></div></article>}):<div className="panel alert-empty"><Bell size={30}/><h2>{tab==='Sin leer'?'Estás al día':'Aún no hay avisos en esta vista'}</h2><p>Las respuestas a tus colaboraciones y las propiedades compatibles con tus solicitudes se guardan aquí.</p></div>}</div></>;
}
