'use client';
import {createContext,useContext,useState,useEffect,useRef,type ReactNode,type SetStateAction,type MouseEvent,type AnchorHTMLAttributes} from 'react';
import {usePathname} from 'next/navigation';
import {toast} from 'sonner';
import {profiles,profile,seedDemo,forActor,type ActorId,type DemoData,type DemoAction,type Notification,type AdvisorProfile} from '@/lib/demo-model';
import {type Property,type Requirement,type Collaboration} from '@/lib/real-estate';
import type {Member} from '@/lib/membership';
type Setter<T>=(updater:SetStateAction<T>)=>Promise<boolean>;
type DemoContext={guest:boolean;notifications:Notification[];member:Member;networkProfiles:AdvisorProfile[];properties:Property[];requirements:Requirement[];collaborations:Collaboration[];saved:string[];actorId:ActorId;actor:ReturnType<typeof profile>;switchProfile:(id:ActorId)=>void;pathname:string;query:string;navigate:(href:string)=>void;loading:boolean;saving:boolean;error:string;refresh:()=>Promise<void>;reqId:string;setReqId:(id:string)=>void;collabTab:string;setCollabTab:(tab:string)=>void;setProperties:Setter<Property[]>;setRequirements:Setter<Requirement[]>;setCollaborations:Setter<Collaboration[]>;setSaved:Setter<string[]>;sendRequest:(p:Property,message:string,requirementId:string)=>Promise<string|null>;runAction:(action:DemoAction)=>Promise<boolean>};
const Context=createContext<DemoContext|null>(null);
const sections=['/inventario','/alertas','/administracion','/solicitudes','/requerimientos','/colaboraciones','/mis-propiedades','/red','/perfil','/niveles'];
const guestSections=['/inventario','/solicitudes','/alertas','/colaboraciones','/red','/niveles'];
const sectionPath=(path:string)=>path.startsWith('/explorar')?(path.replace('/explorar','')||'/inventario'):path.replace('/requerimientos','/solicitudes');
export function DemoProvider({children,member,guest=false,initialData}:{children:ReactNode;member:Member;guest?:boolean;initialData?:DemoData}){
 const initialPath=sectionPath(usePathname()||'/inventario');const [pathname,setPathname]=useState(initialPath);const [query,setQuery]=useState('');
 const [data,setData]=useState<DemoData>(()=>initialData||({...seedDemo(),profiles:[{id:member.id,name:member.name,agency:member.agency,initials:member.name.split(' ').slice(0,2).map(s=>s[0]).join(''),email:member.email,phone:member.phone,role:member.role==='admin'?'Administrador':'Asesor',color:'#d9f56b',active:true}]}));const [actorId,setActorId]=useState<ActorId>(member.id);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const [reqByActor,setReqByActor]=useState<Record<string,string>>({alejandro:'REQ-01',mariana:'REQ-02'});const [collabTab,setCollabTab]=useState(guest?'Enviada':'Recibida');const actor=profile(actorId,data.profiles);const current=forActor(data,actorId);
 const noticeRef=useRef<{actor:string;ids:Set<string>}|null>(null);
 useEffect(()=>{if(loading)return;const ids=new Set(current.notifications.map(n=>n.id));if(noticeRef.current?.actor===actorId){const arriving=current.notifications.filter(n=>!n.readAt&&!noticeRef.current!.ids.has(n.id));if(arriving.length)toast.success(arriving.length===1?(arriving[0].kind==='collaboration'?arriving[0].title:'Nueva posible coincidencia para '+arriving[0].requirementReference):arriving.length+' nuevas notificaciones',{description:'Consulta la campana de alertas.'});}noticeRef.current={actor:actorId,ids};},[data,actorId,loading]);
 const dataRef=useRef(data);dataRef.current=data;const busyRef=useRef(false);
 async function refresh(){if(guest){setLoading(false);return;}try{const response=await fetch('/api/demo',{cache:'no-store'});const d=await response.json() as DemoData & {error?:string};if(!response.ok){if(response.status===401||response.status===403)window.location.assign('/registro');throw Error(d.error||'No se pudo cargar la plataforma.');}if(d.version>=dataRef.current.version){dataRef.current=d;setData(d)}setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar la demo.')}finally{setLoading(false)}}
 useEffect(()=>{if(guest){setPathname(sectionPath(window.location.pathname));setQuery(window.location.search);setLoading(false);const pop=()=>{setPathname(sectionPath(window.location.pathname));setQuery(window.location.search)};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)}let selected:string|null=null;try{selected=sessionStorage.getItem('red-demo-profile-v2')}catch{}if(selected===member.id||member.role==='admin'&&profiles.some(p=>p.id===selected))setActorId(selected as ActorId);setPathname(window.location.pathname.replace('/requerimientos','/solicitudes'));setQuery(window.location.search);void refresh();const pop=()=>{setPathname(window.location.pathname.replace('/requerimientos','/solicitudes'));setQuery(window.location.search)};const focus=()=>{if(document.visibilityState==='visible'&&!busyRef.current)void refresh()};window.addEventListener('popstate',pop);window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);const timer=setInterval(focus,15000);return ()=>{window.removeEventListener('popstate',pop);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);clearInterval(timer)}},[]);
 function navigate(href:string){const url=new URL(href,window.location.origin);const section=sectionPath(url.pathname);if(url.origin!==window.location.origin||!(guest?guestSections:sections).includes(section))return;if(guest)url.pathname=section==='/inventario'?'/explorar':'/explorar'+section;if(window.location.pathname+window.location.search!==url.pathname+url.search)window.history.pushState(null,'',url.pathname+url.search);setPathname(sectionPath(url.pathname));setQuery(url.search);window.scrollTo({top:0,behavior:'instant'})}
 function switchProfile(id:ActorId){if(guest||id===actorId||member.role!=='admin'||id!==member.id&&!profiles.some(p=>p.id===id))return;setActorId(id);try{sessionStorage.setItem('red-demo-profile-v2',id)}catch{}setCollabTab('Recibida');void refresh()}
 async function runAction(action:DemoAction){if(guest){toast('Solicita acceso para participar en la red.');return false;}if(busyRef.current){toast('Espera a que termine el guardado.');return false}if(loading||error){toast.error('Primero vuelve a cargar la demo.');return false}busyRef.current=true;setSaving(true);try{const response=await fetch('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action)});const d=await response.json() as DemoData & {error?:string};if(!response.ok)throw Error(d.error||'No se pudo guardar.');dataRef.current=d;setData(d);return true}catch(e){toast.error(e instanceof Error?e.message:'No pudimos guardar. Vuelve a intentar.');return false}finally{busyRef.current=false;setSaving(false)}}
 const setProperties:Setter<Property[]>=async updater=>{const old=forActor(dataRef.current,actorId).properties;const next=typeof updater==='function'?updater(old):updater;const changed=next.find(p=>p!==old.find(x=>x.id===p.id));if(!changed)return true;const previous=old.find(x=>x.id===changed.id);const minimal=(p:Property)=>JSON.stringify({...p,status:undefined,confirmed:undefined});if(previous&&minimal(previous)===minimal(changed))return runAction({type:'property_status',actorId,propertyId:changed.id,status:changed.status});return runAction({type:'property',actorId,property:{...changed,photos:changed.photos?.length?changed.photos:[changed.image]} as Extract<DemoAction,{type:'property'}>['property']})};
 const setRequirements:Setter<Requirement[]>=async updater=>{const old=forActor(dataRef.current,actorId).requirements;const next=typeof updater==='function'?updater(old):updater;const r=next.find(r=>r!==old.find(x=>x.id===r.id));if(!r)return true;const {history,createdAt,updatedAt,ownerId,...payload}=r;return runAction({type:'requirement',actorId,requirement:payload as Extract<DemoAction,{type:'requirement'}>['requirement']})};
 const setCollaborations:Setter<Collaboration[]>=async updater=>{const old=forActor(dataRef.current,actorId).collaborations;const next=typeof updater==='function'?updater(old):updater;const c=next.find(c=>c!==old.find(x=>x.id===c.id));if(!c)return true;return runAction({type:'respond',actorId,collaborationId:c.id,status:c.status as 'Aceptada'|'Rechazada'|'Aclaración'|'Pendiente',message:c.clarification||''})};
 const setSaved:Setter<string[]>=async updater=>{const old=dataRef.current.saved[actorId]||[];const next=typeof updater==='function'?updater(old):updater;const change=next.find(id=>!old.includes(id))||old.find(id=>!next.includes(id));return change?runAction({type:'save',actorId,propertyId:change,save:next.includes(change)}):true};
 async function sendRequest(p:Property,message:string,requirementId:string){const ok=await runAction({type:'request',actorId,id:'COL-'+crypto.randomUUID().slice(0,8),propertyId:p.id,message,requirementId});return ok?null:'La solicitud no se guardó. Revisa el aviso e inténtalo de nuevo.'}
 return <Context.Provider value={{...current,guest,member,networkProfiles:Array.from(new Map([...(guest?[]:profiles),...(data.profiles||[])].map(p=>[p.id,p])).values()),actorId,actor,switchProfile,pathname,query,navigate,loading,saving,error,refresh,reqId:reqByActor[actorId]||current.requirements[0]?.id||'',setReqId:id=>setReqByActor(old=>({...old,[actorId]:id})),collabTab,setCollabTab,setProperties,setRequirements,setCollaborations,setSaved,sendRequest,runAction}}>{children}</Context.Provider>
}
export function useDemo(){const c=useContext(Context);if(!c)throw Error('Falta el contexto de demo.');return c;}
export function DemoLink({href,children,onClick,...rest}:AnchorHTMLAttributes<HTMLAnchorElement>&{href:string}){const {navigate,guest}=useDemo();const targetHref=guest&&guestSections.includes(href.split('?')[0])?'/explorar'+(href.startsWith('/inventario')?href.replace('/inventario',''):href):href;function click(e:MouseEvent<HTMLAnchorElement>){onClick?.(e);if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||rest.target&&rest.target!=='_self')return;if(!href.startsWith('/'))return;e.preventDefault();navigate(href)}return <a href={targetHref} onClick={click} {...rest}>{children}</a>}
