'use client';
import {useRef,useState,useEffect} from 'react';
import {ImagePlus,Trash2,LoaderCircle,RefreshCw} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {useDemo} from '@/components/platform-data';
import {toast} from 'sonner';
type Photo={id:string;preview:string;url?:string;file?:File;status:'ready'|'uploading'|'error'};
async function prepare(file:File){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Usa fotografías JPG, PNG o WebP.');
 if(file.size>8*1024*1024)throw Error('Cada fotografía puede pesar hasta 8 MB.');
 const image=await createImageBitmap(file);const scale=Math.min(1,1920/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const ctx=canvas.getContext('2d');if(!ctx){image.close();return file}ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);image.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.86));return blob?new File([blob],file.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'}):file;
}
export function PropertyPhotos({initial,cover,onChange,onBusy}:{initial:string[];cover:string;onChange:(urls:string[],cover:string)=>void;onBusy:(busy:boolean)=>void}){
 const {actorId}=useDemo();const [photos,setPhotos]=useState<Photo[]>(()=>initial.map((url,i)=>({id:'existing-'+i,preview:url,url,status:'ready'})));const [selected,setSelected]=useState(cover||initial[0]||'');const input=useRef<HTMLInputElement>(null);const allocated=useRef<string[]>([]);const photosRef=useRef(photos);photosRef.current=photos;
 useEffect(()=>()=>allocated.current.forEach(URL.revokeObjectURL),[]);
 useEffect(()=>{const ready=photos.filter(p=>p.status==='ready'&&p.url).map(p=>p.url!);if(ready.length&&!ready.includes(selected))setSelected(ready[0]);onChange(ready,ready.includes(selected)?selected:ready[0]||'');onBusy(photos.some(p=>p.status!=='ready'))},[photos,selected]);
 async function upload(photo:Photo){if(!photo.file)return;setPhotos(old=>old.map(p=>p.id===photo.id?{...p,status:'uploading'}:p));try{const file=await prepare(photo.file);const form=new FormData();form.set('photo',file);const response=await fetch('/api/photos',{method:'POST',headers:{'X-Demo-Profile':actorId},body:form});const result=await response.json() as {url:string;error?:string};if(!response.ok)throw Error(result.error||'No se pudo subir la foto.');setPhotos(old=>old.map(p=>p.id===photo.id?{...p,url:result.url,status:'ready'}:p));setSelected(old=>old||result.url)}catch(e){setPhotos(old=>old.map(p=>p.id===photo.id?{...p,status:'error'}:p));toast.error(e instanceof Error?e.message:'No se pudo subir la fotografía.')}}
 async function add(files:FileList|null){if(!files)return;const room=10-photosRef.current.length;const all=Array.from(files);if(all.length>room)toast('Puedes agregar hasta 10 fotografías por propiedad.');const items:Photo[]=all.slice(0,room).filter(f=>{if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8*1024*1024){toast.error(f.name+': usa JPG, PNG o WebP de hasta 8 MB.');return false}return true}).map(file=>{const preview=URL.createObjectURL(file);allocated.current.push(preview);return {id:crypto.randomUUID(),preview,file,status:'uploading'}});setPhotos(old=>[...old,...items]);for(const p of items)await upload(p);if(input.current)input.current.value=''}
 return <section className="photo-editor"><div className="row between"><div><h3>Fotografías</h3><p>Mínimo 8, máximo 10 · JPG, PNG o WebP · 8 MB por foto</p></div><button type="button" className="btn secondary small" onClick={()=>input.current?.click()} disabled={photos.length>=10||photos.some(p=>p.status==='uploading')}><ImagePlus size={16}/>Agregar fotos</button></div><input ref={input} type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>void add(e.target.files)} className="sr-only" aria-label="Seleccionar fotografías de la propiedad"/>{!photos.length?<button type="button" className="photo-drop" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void add(e.dataTransfer.files)}}><ImagePlus size={26}/><strong>Selecciona o arrastra tus fotos aquí</strong><span>Elige después cuál será la portada.</span></button>:<RadioGroup value={selected} onValueChange={setSelected} className="photo-tiles">{photos.map((p,i)=><div className={'photo-tile'+(p.url===selected?' cover':'')} key={p.id}><img src={p.preview} alt={'Fotografía '+(i+1)}/><button className="remove-photo" type="button" aria-label={'Quitar fotografía '+(i+1)} onClick={()=>setPhotos(old=>old.filter(x=>x.id!==p.id))} disabled={p.status==='uploading'}><Trash2 size={14}/></button>{p.status==='ready'?<label className="photo-cover"><RadioGroupItem value={p.url!}/>{p.url===selected?'Portada':'Usar de portada'}</label>:<div className="photo-progress">{p.status==='uploading'?<><LoaderCircle size={14} className="spin"/>Guardando…</>:<button type="button" className="text-link row" onClick={()=>void upload(p)}><RefreshCw size={13}/>Reintentar</button>}</div>}</div>)}</RadioGroup>}<p className="form-caption">{photos.filter(p=>p.status==='ready').length} / 8 fotos mínimas guardadas. {photos.filter(p=>p.status==='ready').length<8?'Agrega '+(8-photos.filter(p=>p.status==='ready').length)+' más para poder publicar.':'Galería lista para publicar.'}</p></section>
}
export function PhotoGallery({photos,title}:{photos:string[];title:string}){const [index,setIndex]=useState(0);const source=photos[Math.min(index,photos.length-1)];return <div className="property-gallery"><img className="detail-image" src={source} alt={title+' · fotografía '+(index+1)}/>{photos.length>1&&<div className="gallery-thumbs" role="group" aria-label="Fotografías de la propiedad">{photos.map((url,i)=><button type="button" aria-label={'Ver fotografía '+(i+1)} aria-pressed={index===i} className={index===i?'active':''} key={url} onClick={()=>setIndex(i)}><img src={url} alt=""/></button>)}<span>{index+1} / {photos.length}</span></div>}</div>}
