'use client';
import {useState,useId,useEffect,type FormEvent} from 'react';
import {Bell,CheckCheck,Clock3,FileText,Layers,Plus,Search} from 'lucide-react';
import {toast} from 'sonner';
import {useDemo} from './platform-data';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {getMatches,money,propertyTypes,type Requirement,type Property} from '@/lib/real-estate';
import {criteriaLabels,requirementCriteria,featureAliases,parsePropertySearch,type SearchCriteria} from '@/lib/property-search';
const date=(s?:string)=>s?new Date(s).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'}):'Fecha no registrada';
export function CriteriaChips({labels}:{labels:string[]}){return <div className="criteria-chips">{labels.map((s,i)=><span key={i}>{s}</span>)}</div>}
function Choice({label,value,onChange,items}:{label:string;value:string;onChange:(s:string)=>void;items:string[]}){return <div className="field"><label>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger className="filter-select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>}
function Input({label,name,value,onChange,type='text',step,placeholder,required=false,full=false,maxLength}:{label:string;name:string;value:string|number;onChange:(s:string)=>void;type?:string;step?:string;placeholder?:string;required?:boolean;full?:boolean;maxLength?:number}){const id=useId();return <div className={'field'+(full?' full':'')}><label htmlFor={id}>{label}</label><input id={id} name={name} value={value} onChange={e=>onChange(e.target.value)} type={type} min={type==='number'?0:undefined} step={step} required={required} placeholder={placeholder} maxLength={maxLength}/></div>}
export function RequirementForm({editing,search,searchText='',onSaved,onCancel}:{editing?:Requirement|null;search?:SearchCriteria;searchText?:string;onSaved:()=>void;onCancel:()=>void}){
 const {actorId,properties,setRequirements,setReqId,saving,loading,error,navigate}=useDemo();
 const [r,setR]=useState<Requirement>(()=>editing||{id:'REQ-'+crypto.randomUUID().slice(0,8).toUpperCase(),ownerId:actorId,reference:searchText.slice(0,140),operation:search?.operation||'Indistinta',type:search?.type||'Indistinto',zones:search?.zones||[],budget:search?.budget||0,beds:search?.beds||0,baths:search?.baths||0,parking:search?.parking||0,minArea:search?.minArea||0,minLand:search?.minLand||0,garden:search?.gardenMode==='Con jardín',gardenMode:search?.gardenMode||'Indiferente',poolMode:search?.poolMode||'Indiferente',furnishing:search?.furnishing||'Indistinto',features:search?.features||[],keywords:search?.keywords||'',searchText,status:'Activo',flexBudget:false,alerts:true});
 const [zones,setZones]=useState(r.zones.join(', '));const [phrase,setPhrase]=useState(searchText||r.searchText||'');function applyPhrase(){const parsed=parsePropertySearch(phrase,properties.map(p=>p.zone));setR(old=>({...old,...parsed,operation:parsed.operation||'Indistinta',type:parsed.type||'Indistinto',budget:parsed.budget||0,beds:parsed.beds||0,parking:parsed.parking||0,garden:parsed.gardenMode==='Con jardín',gardenMode:parsed.gardenMode||'Indiferente',searchText:phrase,reference:old.reference||phrase.slice(0,140)}));setZones(parsed.zones.join(', '));}
 function update<K extends keyof Requirement>(key:K,value:Requirement[K]){setR(old=>({...old,[key]:value}))}
 const draft={...r,zones:zones.split(',').map(s=>s.trim()).filter(Boolean),ownerId:actorId};const count=getMatches({...draft,status:'Activo'},properties).length;
 async function submit(e:FormEvent){e.preventDefault();if(!await setRequirements(old=>editing?old.map(x=>x.id===r.id?draft:x):[draft,...old]))return;setReqId(r.id);onSaved();navigate('/solicitudes');toast.success(editing?'Solicitud actualizada':count?'Solicitud guardada con opciones compatibles':'Solicitud guardada en espera');}
 return <form onSubmit={submit} className="search-request-form"><div className="save-search-guide"><strong>Una búsqueda guardada para tu cliente</strong><p>Describe lo que necesita, revisa los criterios y guarda. Si todavía no hay opciones, la solicitud queda activa en espera y te avisaremos cuando aparezca una compatible.</p></div>{!editing&&<div className="request-phrase"><label htmlFor="request-phrase">¿Qué necesita tu cliente?</label><div className="row"><input id="request-phrase" value={phrase} maxLength={500} onChange={e=>setPhrase(e.target.value)} placeholder="Ej. casa con jardín en El Molino hasta 7 millones"/><button className="btn secondary small" type="button" disabled={!phrase.trim()} onClick={applyPhrase}>Aplicar descripción</button></div><small>También puedes completar o ajustar los campos directamente.</small></div>}<div className="form-grid">
 <Input label="Nombre para recordar esta búsqueda" name="reference" value={r.reference} onChange={v=>update('reference',v)} required maxLength={140} placeholder="Ej. Familia · casa con jardín en El Molino" full/>
 <Choice label="Operación solicitada" value={r.operation} onChange={v=>update('operation',v as Requirement['operation'])} items={['Indistinta','Venta','Renta']}/><Choice label="Tipo solicitado" value={r.type} onChange={v=>update('type',v)} items={['Indistinto',...propertyTypes]}/>
 <Input label="Ubicaciones aceptadas · separadas por coma" name="zones" value={zones} onChange={setZones} placeholder="Colonia, zona, CP o calle · vacío para cualquier ubicación" full maxLength={900}/>
 <Input label="Presupuesto máximo · MXN" name="budget" value={r.budget||''} onChange={v=>update('budget',Number(v))} type="number" placeholder="Sin límite"/>
 <Input label="Recámaras mínimas" name="beds" value={r.beds} onChange={v=>update('beds',Number(v))} type="number"/>
 <Input label="Estacionamientos mínimos" name="parking" value={r.parking} onChange={v=>update('parking',Number(v))} type="number"/>
 <Choice label="Jardín" value={r.gardenMode||(r.garden?'Con jardín':'Indiferente')} onChange={v=>{update('gardenMode',v as Requirement['gardenMode']);update('garden',v==='Con jardín')}} items={['Indiferente','Con jardín','Sin jardín']}/>
 </div><details className="client-details-editor"><summary>Más especificaciones</summary><div className="form-grid">
 <Input label="Baños mínimos" name="baths" value={r.baths||0} onChange={v=>update('baths',Number(v))} type="number" step="0.5"/><Choice label="Alberca" value={r.poolMode||'Indiferente'} onChange={v=>update('poolMode',v as Requirement['poolMode'])} items={['Indiferente','Con alberca','Sin alberca']}/>
 <Input label="Construcción mínima · m²" name="minArea" value={r.minArea||0} onChange={v=>update('minArea',Number(v))} type="number"/><Input label="Terreno mínimo · m²" name="minLand" value={r.minLand||0} onChange={v=>update('minLand',Number(v))} type="number"/>
 <Choice label="Mobiliario" value={r.furnishing||'Indistinto'} onChange={v=>update('furnishing',v as Requirement['furnishing'])} items={['Indistinto','Amueblado','Sin muebles']}/>
 <Input label="Otras palabras clave" name="keywords" value={r.keywords||''} onChange={v=>update('keywords',v)} maxLength={500} placeholder="Ej. remodelada"/>
 <div className="full feature-checks">{Object.keys(featureAliases).map(s=><label className="inline-check" key={s}><Checkbox checked={r.features?.includes(s)||false} onCheckedChange={v=>update('features',v?[...(r.features||[]),s]:(r.features||[]).filter(x=>x!==s))}/>{s}</label>)}</div>
 </div><p className="form-caption">Las características se comprueban con los datos y la descripción de cada ficha.</p></details>
 <div className="request-alert-setting"><label className="inline-check"><Switch checked={r.alerts} onCheckedChange={v=>update('alerts',v)} aria-label="Alertas de coincidencias"/><span><strong>Avisarme de posibles coincidencias</strong><small>La alerta se guarda en tu campana al aparecer una opción compatible.</small></span></label></div>
 <label className="inline-check"><Checkbox checked={r.flexBudget} onCheckedChange={v=>update('flexBudget',!!v)} disabled={!r.budget}/>Mostrar aparte alternativas hasta 5% sobre el presupuesto</label>
 <div className={'request-preview'+(count?' has-matches':'')} role="status">{count?<Layers size={19}/>:<Clock3 size={19}/>}<div><strong>{count?count+' posibles coincidencias ahora':'Se guardará en espera'}</strong><p>{count?'Consulta las fichas y confirma los detalles con el asesor.':'Tu solicitud seguirá activa aunque todavía no haya propiedades compatibles.'}</p></div></div>
 <p className="form-caption">Usa una referencia interna. Evita datos personales del cliente. Puedes pausar o resolver la solicitud en cualquier momento.</p>
 <div className="form-footer"><button className="btn secondary" type="button" onClick={onCancel}>Cancelar</button><button className="btn" disabled={saving||loading||!!error}>{saving?'Guardando…':editing?'Guardar cambios':r.alerts?'Guardar búsqueda y activar alertas':'Guardar búsqueda'}</button></div></form>;
}
export function RequestsPage({onNew,onEdit,onProperty}:{onNew:()=>void;onEdit:(r:Requirement)=>void;onProperty:(p:Property)=>void}){
 const {guest,requirements,properties,notifications,setRequirements,setReqId,navigate,saving,loading,error,query}=useDemo();const [expanded,setExpanded]=useState<string|null>(null);useEffect(()=>{const id=new URLSearchParams(query).get('solicitud');if(id)setExpanded(id)},[query]);const [tab,setTab]=useState('Activas');
 const active=requirements.filter(r=>r.status==='Activo');const waiting=active.filter(r=>!getMatches(r,properties).length);const list=requirements.filter(r=>tab==='Todas'||tab==='Activas'&&r.status==='Activo'||tab==='En espera'&&r.status==='Activo'&&!getMatches(r,properties).length||tab==='Historial'&&r.status!=='Activo');
 const blocked=guest||saving||loading||!!error;
 async function change(r:Requirement,patch:Partial<Requirement>){if(await setRequirements(old=>old.map(x=>x.id===r.id?{...x,...patch}:x)))toast.success('Solicitud actualizada');}
 return <><div className="request-summary"><div><FileText size={20}/><strong>{requirements.length}</strong><span>Búsquedas guardadas</span></div><div><Clock3 size={20}/><strong>{waiting.length}</strong><span>En espera de una opción</span></div><div><Layers size={20}/><strong>{active.length-waiting.length}</strong><span>Con posibles coincidencias</span></div></div>
 <div className="request-explainer"><Bell size={18}/><p>{guest?'Ejemplo de búsquedas guardadas: una solicitud conserva su historial y espera opciones compatibles. Solicita acceso para crear las tuyas.':'Tu búsqueda sigue activa. Cuando otro asesor publique una propiedad compatible, recibirás una alerta aquí. El historial conserva tus solicitudes y los cambios que haces.'}</p></div>
 <div className="results-header request-views"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line">{['Activas','En espera','Historial','Todas'].map(s=><TabsTrigger key={s} value={s}>{s}</TabsTrigger>)}</TabsList></Tabs><span className="results-caption">{list.length} solicitudes · {guest?'ejemplo':'tu perfil'}</span></div>
 {list.length?<div className="request-grid">{list.map(r=>{const matches=getMatches(r,properties);const unread=notifications.filter(n=>n.kind!=='collaboration'&&n.requirementId===r.id&&!n.readAt).length;return <article className="panel request-history-card" key={r.id}><div className="row between"><span className={'tag '+(r.status==='Activo'?matches.length?'':'amber':'gray')}>{r.status==='Activo'?matches.length?'Con coincidencias':'En espera':r.status}</span>{unread>0&&<span className="tag">{unread} alertas nuevas</span>}</div><h2>{r.reference}</h2><p className="request-budget">{r.budget?'Hasta '+money(r.budget):'Sin límite de presupuesto'} <small>MXN{r.operation==='Renta'?' / mes':''}</small></p><CriteriaChips labels={criteriaLabels({...requirementCriteria(r),budget:undefined})}/>{!r.zones.length&&<p className="form-caption">Cualquier zona</p>}
 <div className="request-card-status"><span>{r.status==='Activo'?matches.length+' opciones compatibles':'La búsqueda está detenida'}</span><label className="inline-check"><Switch aria-label={'Alertas para '+r.reference} checked={r.alerts} disabled={blocked} onCheckedChange={v=>void change(r,{alerts:v})}/>Alertas {r.alerts?'activadas':'desactivadas'}</label></div>
 <div className="request-card-actions"><button className="btn secondary small" onClick={()=>{setReqId(r.id);setExpanded(old=>old===r.id?null:r.id)}}>{expanded===r.id?'Ocultar opciones':'Ver opciones ('+matches.length+')'}</button><button className="btn secondary small" disabled={blocked} onClick={()=>onEdit(r)}>Editar</button>{r.status==='Activo'?<><button className="text-link" disabled={blocked} onClick={()=>void change(r,{status:'Pausado'})}>Pausar</button><button className="text-link" disabled={blocked} onClick={()=>void change(r,{status:'Resuelto'})}>Marcar resuelta</button></>:<button className="text-link" disabled={blocked} onClick={()=>void change(r,{status:'Activo'})}>Reactivar</button>}</div>
 {expanded===r.id&&<div className="request-inline-options">{matches.length?matches.map(p=><button key={p.id} className="request-option" onClick={()=>onProperty(p)}><img src={p.image} alt=""/><span><strong>{p.title}</strong><small>{money(p.price)} · {p.zone}</small><small>{p.owner} · Abrir ficha</small></span></button>):<p>Seguimos buscando. Cuando se publique una opción compatible, aparecerá aquí y recibirás una alerta si están activadas.</p>}</div>}<details className="request-history"><summary>Historial de la solicitud <span>{r.history?.length||0} cambios</span></summary><p>Creada: {date(r.createdAt)}</p>{r.searchText&&<p>Búsqueda original: “{r.searchText}”</p>}{r.history?.length?<ol>{[...r.history].reverse().map((event,i)=><li key={i}><strong>{event.text}</strong><small>{date(event.at)}</small><CriteriaChips labels={event.criteria}/></li>)}</ol>:<p>Solicitud anterior al registro de historial. Sus próximos cambios se guardarán aquí.</p>}</details>
 </article>})}</div>:<Empty className="panel"><EmptyHeader><EmptyMedia variant="icon"><Search/></EmptyMedia><EmptyTitle>{tab==='En espera'?'No hay solicitudes en espera':'Aún no hay solicitudes en esta vista'}</EmptyTitle><EmptyDescription>Guarda lo que busca tu cliente. La solicitud permanece aunque hoy no haya opciones.</EmptyDescription></EmptyHeader><button className="btn" onClick={onNew} disabled={blocked}><Plus size={16}/>Nueva solicitud</button></Empty>}
 </>;
}
