import {bindings} from './bindings';
import {AccessError,emptyAccess,ensureOwner,memberFor,type AccessData,type Identity,type Member} from '@/lib/membership';
export async function readAccess():Promise<AccessData>{const {db}=bindings();let row=await db.prepare('SELECT data, version FROM membership_state WHERE id = ?').bind('network-access-v1').first<{data:string;version:number}>();if(!row){await db.prepare('INSERT OR IGNORE INTO membership_state (id, data, version, updated_at) VALUES (?, ?, ?, ?)').bind('network-access-v1',JSON.stringify(emptyAccess()),0,new Date().toISOString()).run();row=await db.prepare('SELECT data, version FROM membership_state WHERE id = ?').bind('network-access-v1').first<{data:string;version:number}>();}if(!row)throw Error('El registro no está disponible.');return {...JSON.parse(row.data),version:row.version};}
export async function mutateAccess(fn:(data:AccessData)=>AccessData){const {db}=bindings();for(let attempt=0;attempt<4;attempt++){const old=await readAccess();const next=fn(old);if(next.version===old.version)return old;const result=await db.prepare('UPDATE membership_state SET data = ?, version = ?, updated_at = ? WHERE id = ? AND version = ?').bind(JSON.stringify(next),next.version,new Date().toISOString(),'network-access-v1',old.version).run();if(result.meta.changes===1)return next;}throw new AccessError('Otra acción modificó el registro. Vuelve a intentar.',409);}
export function requestIdentity(request:Request):Identity|null{const userId=request.headers.get('oai-authenticated-user-id'),email=request.headers.get('oai-authenticated-user-email');if(!userId||!email)return null;return {userId,email,displayName:email};}
export async function accessFor(user:Identity|null){if(!user)return {user:null,member:null};const data=await mutateAccess(d=>ensureOwner(d,user));return {user,member:memberFor(data,user)};}
export async function requireMember(request:Request):Promise<Member>{const {member}=await accessFor(requestIdentity(request));if(!member||member.status!=='Activo')throw new AccessError('Tu acceso todavía no está autorizado.',member?403:401);return member;}
export async function requireAdmin(request:Request){const member=await requireMember(request);if(member.role!=='admin')throw new AccessError('Este panel requiere permisos de administrador.');return member;}
export function authorizeActor(member:Member,actorId:string){if(actorId!==member.id&&!(member.role==='admin'&&['alejandro','mariana'].includes(actorId)))throw new AccessError('Este perfil no corresponde a tu cuenta.');}
